steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/dew-p1-sample-app:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/${PROJECT_ID}/dew-p1-sample-app:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'dew-p1-sample-app'
    - '--region=asia-east1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--service-account=dew-p1-sample-app@seventh-dryad-274514.iam.gserviceaccount.com'
    - '--image=gcr.io/${PROJECT_ID}/dew-p1-sample-app:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
